name: "Workflow Commands"

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps: 
      - name: "group logging"
        runs: |
          echo "::group::My Group Message"
          echo "Msg 1"
          echo "Msg 2"
          echo "::endgroup::"